// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhw3Tae1Uht5Ie91jcNFElf_ernSslvL0',
    appId: '1:291970661890:web:1aabe544a5ca0f829cb11b',
    messagingSenderId: '291970661890',
    projectId: 'attendance-app-7c01e',
    authDomain: 'attendance-app-7c01e.firebaseapp.com',
    storageBucket: 'attendance-app-7c01e.appspot.com',
    measurementId: 'G-2JVQYYJLVW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7nKPl5hY64F9RHCwJPBTOfKS_dQYd4EU',
    appId: '1:238323406084:android:abf31d306381d6d832ac51',
    messagingSenderId: '238323406084',
    projectId: 'attendance-app-38a05',
    storageBucket: 'attendance-app-38a05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhGkysDDRZVMfP7JA2k9AWaUfYqW8eIo0',
    appId: '1:291970661890:ios:67ccbe7fec686cb29cb11b',
    messagingSenderId: '291970661890',
    projectId: 'attendance-app-7c01e',
    storageBucket: 'attendance-app-7c01e.appspot.com',
    iosBundleId: 'com.tanjim.attendanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhGkysDDRZVMfP7JA2k9AWaUfYqW8eIo0',
    appId: '1:291970661890:ios:67ccbe7fec686cb29cb11b',
    messagingSenderId: '291970661890',
    projectId: 'attendance-app-7c01e',
    storageBucket: 'attendance-app-7c01e.appspot.com',
    iosBundleId: 'com.tanjim.attendanceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhw3Tae1Uht5Ie91jcNFElf_ernSslvL0',
    appId: '1:291970661890:web:8a61a049ea78ba629cb11b',
    messagingSenderId: '291970661890',
    projectId: 'attendance-app-7c01e',
    authDomain: 'attendance-app-7c01e.firebaseapp.com',
    storageBucket: 'attendance-app-7c01e.appspot.com',
    measurementId: 'G-HYDVH1W9KJ',
  );
}